import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Poppins } from "next/font/google";
import Header from "./components/Header";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Car Rental App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <script
          defer
          src="https://kit.fontawesome.com/a9c21da018.js"
          crossOrigin="anonymous"
        ></script>
      </head>
      <body className={`${poppins.className} bg-[#F8F8F8]`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}